const seedNotes=[
 {title:'Design systems & the art of less',date:'18 JUL 2026',speaker:'Speaker · Maya Chen',people:['MC','JT'],energy:5,color:'note-yellow',metrics:'●●● ○○'},
 {title:'The future of local AI',date:'12 JUL 2026',speaker:'Speaker · Raj Patel',people:['RP','SK','+3'],energy:4,color:'note-lav',metrics:'●●●● ○'},
 {title:'Founders after dark',date:'04 JUL 2026',speaker:'Speaker · Lina Wu',people:['LW','OB'],energy:5,color:'note-coral',metrics:'●● ○○○'},
 {title:'Making a career pivot',date:'28 JUN 2026',speaker:'Speaker · Tom Ellis',people:['TE','NA','+2'],energy:3,color:'note-mint',metrics:'●●● ○○'},
 {title:'Better questions, better work',date:'19 JUN 2026',speaker:'Speaker · Alex Morgan',people:['AM'],energy:4,color:'note-blue',metrics:'●●●● ○'},
 {title:'Coffee & community',date:'03 JUN 2026',speaker:'Speaker · not logged',people:['JM','RK'],energy:5,color:'note-yellow',metrics:'●●●●●'}
];
let notes=JSON.parse(localStorage.getItem('netit-notes')||'null')||seedNotes;
const grid=document.querySelector('#notesGrid'); const backdrop=document.querySelector('#modalBackdrop'); const modal=document.querySelector('#modalContent'); const toast=document.querySelector('#toast');
function renderJourney(){const count=notes.length;const countEl=document.querySelector('#meetupCount');const titleEl=document.querySelector('#journeyTitle');const pathEl=document.querySelector('#pathway');if(!countEl||!titleEl||!pathEl)return;countEl.innerHTML=`${count} <small>meetups</small>`;titleEl.textContent=`${count} step${count===1?'':'s'} so far`;const visible=Math.min(Math.max(count,1),8);pathEl.innerHTML=Array.from({length:visible},(_,i)=>`<div class="step-stone"><span>${i+1}</span></div>`).join('')}
function renderInsightPath(){const card=document.querySelector('#insightsView .chart-card');if(!card)return;const items=notes.slice(0,8).reverse();card.innerHTML=`<div class="dot-path-header"><div><p class="eyebrow">YOUR MEETUP PATH</p><h2>Every hello leaves a mark.</h2></div><span class="dot-path-count">${notes.length} total</span></div><div class="dot-path" aria-label="Meetup participation path">${items.map((n,i)=>{const num=i+1;const suffix=num===1?'st':num===2?'nd':num===3?'rd':'th';return `<div class="meetup-node ${i===items.length-1?'latest':''}"><div class="node-dot"><span>${num}</span></div><strong>${num}${suffix} meetup</strong><small>${n.title}</small></div>`}).join('')}</div><p class="dot-path-caption">One dot for every time you showed up. The line gets longer with you.</p>`}
function renderNotes(){grid.innerHTML=notes.map((n,i)=>`<article class="note ${n.color}" data-index="${i}"><div class="note-top"><span>${n.date}</span><span>•••</span></div><h3>${n.title}</h3><div class="speaker">${n.speaker}</div><div class="note-footer"><div class="tags">${n.people.map(p=>`<span class="tag">${p}</span>`).join('')}</div><span class="metric-line">${n.metrics}</span></div></article>`).join('');document.querySelector('#noteCount').textContent=notes.length;renderJourney();renderInsightPath();grid.querySelectorAll('.note').forEach(el=>el.onclick=()=>openNote(Number(el.dataset.index)))}
function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
function openModal(content){modal.innerHTML=content;backdrop.hidden=false;modal.querySelector('.close-btn')?.addEventListener('click',closeModal);backdrop.onclick=e=>{if(e.target===backdrop)closeModal()}}
function closeModal(){backdrop.hidden=true}
function openQuestions(){const topic=(document.querySelector('#topicInput').value||'this meetup').trim();const qs=[`What is changing fastest in ${topic} right now?`,`What tools or habits help you do your best ${topic} work?`,`What is one problem in ${topic} you are excited to solve?`,`What brought you to this meetup today?`,`What is something outside of work you have been enjoying lately?`];openModal(`<div class="modal-header"><div><p class="eyebrow">QUICK WAYS IN</p><h2>Your conversation starters</h2></div><button class="close-btn">×</button></div><p class="modal-sub">A few prompts about <b>${topic}</b>, ready when you are.</p><div class="question-list">${qs.map((q,i)=>`<div class="question"><small>${i<3?'PROFESSIONAL':'LIGHTHEARTED'}</small><span>${q}</span><button class="copy-btn" data-q="${q.replaceAll('"','&quot;')}">⧉</button></div>`).join('')}</div>`);modal.querySelectorAll('.copy-btn').forEach(btn=>btn.onclick=()=>{navigator.clipboard?.writeText(btn.dataset.q);showToast('Copied to clipboard')})}
function openNote(index){const n=notes[index];openModal(`<div class="modal-header"><div><p class="eyebrow">${n.date}</p><h2>${n.title}</h2></div><button class="close-btn">×</button></div><p class="modal-sub">A light reflection from your networking board.</p><div class="form-grid"><div class="field"><label>PEOPLE MET</label><div class="chips">${n.people.map(p=>`<span class="chip">${p} ×</span>`).join('')}<input placeholder="Add a name + Enter" /></div></div><div class="field"><label>SPEAKER NAME</label><input value="${n.speaker.replace('Speaker · ','')}" /></div><div class="field"><label>VIBE</label><div class="range-row"><span>Professional</span><input type="range" min="1" max="5" value="3" /><span>Casual</span></div></div><div class="field"><label>FOCUS</label><div class="range-row"><span>Insight</span><input type="range" min="1" max="5" value="4" /><span>Chitchat</span></div></div><div class="field"><label>ENERGY</label><div class="energy-picker">${['🔋','🙂','😊','✨','🚀'].map((e,i)=>`<button class="energy-choice ${i===n.energy-1?'selected':''}">${e}</button>`).join('')}</div></div><div class="field"><label>KEY INSIGHT &amp; NEXT ACTION <span style="float:right;color:#a5b0a8">0 / 140</span></label><textarea placeholder="One takeaway. One next move."></textarea></div></div><div class="modal-footer"><button class="outline-btn close-btn">Cancel</button><button class="primary-btn" id="saveEdit">Save note <span>✓</span></button></div>`);modal.querySelectorAll('.energy-choice').forEach(b=>b.onclick=()=>{modal.querySelectorAll('.energy-choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});modal.querySelector('#saveEdit').onclick=()=>{closeModal();showToast('Note saved')};}
function openAdd(){openModal(`<div class="modal-header"><div><p class="eyebrow">A QUICK REFLECTION</p><h2>Journal a meetup</h2></div><button class="close-btn">×</button></div><p class="modal-sub">Keep it light. You can always add more later.</p><div class="form-grid"><div class="field"><label>MEETUP NAME</label><input id="newTitle" placeholder="e.g. Product people & AI" /></div><div class="field"><label>PEOPLE MET</label><div class="chips" id="newChips"><input placeholder="Type a name + Enter" /></div></div><div class="field"><label>SPEAKER NAME</label><input id="newSpeaker" placeholder="Who led the room?" /></div><div class="field"><label>VIBE</label><div class="range-row"><span>Professional</span><input type="range" min="1" max="5" value="3" /><span>Casual</span></div></div><div class="field"><label>FOCUS</label><div class="range-row"><span>Insight</span><input type="range" min="1" max="5" value="3" /><span>Chitchat</span></div></div><div class="field"><label>ENERGY</label><div class="energy-picker">${['🔋','🙂','😊','✨','🚀'].map((e,i)=>`<button class="energy-choice ${i===3?'selected':''}">${e}</button>`).join('')}</div></div><div class="field"><label>KEY INSIGHT &amp; NEXT ACTION <span style="float:right;color:#a5b0a8">0 / 140</span></label><textarea maxlength="140" placeholder="One takeaway. One next move."></textarea></div></div><div class="modal-footer"><button class="outline-btn close-btn">Cancel</button><button class="primary-btn" id="saveNew">Pin to board <span>＋</span></button></div>`);const chips=modal.querySelector('#newChips');const input=chips.querySelector('input');input.onkeydown=e=>{if(e.key==='Enter'&&input.value.trim()){const s=document.createElement('span');s.className='chip';s.textContent=input.value.trim()+' ×';chips.insertBefore(s,input);input.value=''}};modal.querySelectorAll('.energy-choice').forEach(b=>b.onclick=()=>{modal.querySelectorAll('.energy-choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});modal.querySelector('#saveNew').onclick=()=>{const title=modal.querySelector('#newTitle').value.trim()||'A new connection';const people=[...chips.querySelectorAll('.chip')].map(x=>x.textContent.replace(' ×','')).slice(0,3);notes.unshift({title,date:'19 JUL 2026',speaker:'Speaker · '+(modal.querySelector('#newSpeaker').value.trim()||'not logged'),people:people.length?people:['You'],energy:4,color:['note-yellow','note-lav','note-coral','note-mint','note-blue'][Math.floor(Math.random()*5)],metrics:'●●● ○○'});localStorage.setItem('netit-notes',JSON.stringify(notes));renderNotes();closeModal();showToast('Meetup pinned to your board')}}
document.querySelector('#generateBtn').onclick=openQuestions;document.querySelector('#addMeetupBtn').onclick=openAdd;document.querySelector('#reviewBtn').onclick=()=>openNote(0);document.querySelector('#upcomingReview').onclick=()=>openNote(0);document.querySelector('#addUpcomingBtn').onclick=openAdd;document.querySelector('#shareBtn').onclick=()=>{navigator.clipboard?.writeText('I met 18 people across 4 meetups this month with Net-it 🚀');showToast('Achievement copied to share')};document.querySelectorAll('.nav-item').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));document.querySelector(`#${btn.dataset.view}View`).classList.add('active-page');document.querySelector('#viewTitle').textContent=btn.textContent.trim().replace(/^\S+\s/,'')});renderNotes();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
window.addEventListener('DOMContentLoaded',()=>{document.querySelector('#generateHomeBtn').onclick=()=>{document.querySelector('#topicInput').value=document.querySelector('#topicInputHome').value;openQuestions()};document.querySelectorAll('.inline-link').forEach(link=>link.onclick=()=>document.querySelector('[data-view="board"]').click())});
let people=JSON.parse(localStorage.getItem('netit-people')||'null')||[
 {name:'Maya Chen',initials:'MC',meetup:'Design systems & the art of less',keywords:['design systems','writing less','remote rituals'],color:'person-peach'},
 {name:'Raj Patel',initials:'RP',meetup:'The future of local AI',keywords:['local AI','open source','coffee'],color:'person-mint'},
 {name:'Lina Wu',initials:'LW',meetup:'Founders after dark',keywords:['fundraising','night walks'],color:'person-lav'},
 {name:'Tom Ellis',initials:'TE',meetup:'Making a career pivot',keywords:['career pivot','running','portfolio'],color:'person-blue'}
];
window.addEventListener('DOMContentLoaded',()=>{const menuBtn=document.querySelector('#mobileMenuBtn');const sidebar=document.querySelector('.sidebar');menuBtn?.addEventListener('click',()=>sidebar?.classList.toggle('mobile-open'));document.querySelectorAll('.nav-item').forEach(item=>item.addEventListener('click',()=>sidebar?.classList.remove('mobile-open')))})
function renderPeople(){const grid=document.querySelector('#peopleGrid');if(!grid)return;grid.innerHTML=people.map((p,i)=>`<article class="person-card ${p.color}" data-person="${i}"><div class="person-card-top"><div class="person-avatar">${p.initials}</div><span class="person-menu">•••</span></div><h2>${p.name}</h2><p class="person-last">Last met at <b>${p.meetup}</b></p><div class="keyword-list">${p.keywords.map(k=>`<span>${k}</span>`).join('')}</div><div class="person-card-foot"><span>Conversation notes</span><span>→</span></div></article>`).join('');grid.querySelectorAll('.person-card').forEach(card=>card.onclick=()=>openPerson(Number(card.dataset.person)))}
function openPerson(index){const p=index===undefined?{name:'',initials:'',meetup:'',keywords:[]}:people[index];openModal(`<div class="modal-header"><div><p class="eyebrow">A LIGHT PEOPLE NOTE</p><h2>${p.name||'Remember someone'}</h2></div><button class="close-btn">×</button></div><p class="modal-sub">Keep the thread, not a full profile.</p><div class="form-grid"><div class="field"><label>NAME</label><input id="personName" value="${p.name}" placeholder="e.g. Maya Chen" /></div><div class="field"><label>WHERE YOU MET</label><input id="personMeetup" value="${p.meetup}" placeholder="e.g. Product people & AI" /></div><div class="field"><label>CONVERSATION KEYWORDS</label><input id="personKeywords" value="${p.keywords.join(', ')}" placeholder="e.g. local AI, hiking, books" /><p class="field-help">Separate a few words with commas.</p></div></div><div class="modal-footer"><button class="outline-btn close-btn">Cancel</button><button class="primary-btn" id="savePerson">Save person <span>✓</span></button></div>`);modal.querySelector('#savePerson').onclick=()=>{const name=modal.querySelector('#personName').value.trim()||'Someone I met';const keywords=modal.querySelector('#personKeywords').value.split(',').map(k=>k.trim()).filter(Boolean).slice(0,5);const item={name,initials:name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase(),meetup:modal.querySelector('#personMeetup').value.trim()||'A meetup',keywords,color:p.color||'person-peach'};if(index===undefined)people.unshift(item);else people[index]=item;localStorage.setItem('netit-people',JSON.stringify(people));renderPeople();closeModal();showToast('Person note saved')}}
window.addEventListener('DOMContentLoaded',()=>{renderPeople();document.querySelector('#addPersonBtn').onclick=()=>openPerson()});
